name: Deploy Laravel to VPS

on:
   push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "=== CEK FOLDER SEKARANG ==="
            cd /var/www/project-dashboard-business-kss || { echo "Folder tidak ditemukan"; exit 1; }
            pwd
            ls -la
            echo "=== STATUS GIT ==="
            git status
            echo "=== PULL TERBARU ==="
            git pull origin main
            echo "=== DONE ==="
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            npm run build
          EOF
