name: Deploy Laravel to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            echo "==> Navigating to project directory"
            cd /var/www/project-dashboard-business-kss

            echo "==> Checking for uncommitted changes"
            if [ -n "$(git status --porcelain)" ]; then
              echo "⚠️ WARNING: Uncommitted changes detected. Resetting local repo..."
              git reset --hard
              git clean -fd
            fi

            echo "==> Checking out main branch"
            git checkout main

            echo "==> Pulling latest code"
            git pull origin main

            echo "Ensuring SQLite file exists..."
            if [ ! -f database/database.sqlite ]; then
              touch database/database.sqlite
            fi
            
            echo "==> Installing PHP dependencies"
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "==> Running Laravel migrations and optimizations"
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache

            echo "✅ Deployment finished successfully!"
          EOF
